n_nodes: [10, 100, 500, 1000, 2000, 3000, 5000, 7000, 10000]   
min_conn_per_node: .3            
max_iter: 100                               
damping_factor: .85
n_repeat: 50
num_threads: -1

# Instructions: n_nodes, min_conn_per_node and max_iter are Union[int, List[int]]